trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: GitHubMirrorCredentials  # contains github.username and github.pat

steps:
- checkout: self
  fetchDepth: 0  # get full history for mirroring

- script: |
    echo "Adding GitHub remote..."
    git remote add github https://$(github.username):$(github.pat)@github.com/BlackWolves-nl/ProjectReferrerVersioning.git

    echo "Fetching all branches and tags..."
    git fetch origin --prune

    echo "Pushing all remote branches..."
    git push github +refs/remotes/origin/*:refs/heads/*

    echo "Pushing all tags..."
    git push github --prune refs/tags/*:refs/tags/*
  displayName: 'Mirror to GitHub'
