trigger:
  branches:
    include:
      - "*"

pool:
  vmImage: ubuntu-latest

variables:
  - group: GitHubMirrorCredentials  # Contains github.username and github.pat

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  - script: |
      git config --global user.name "Azure DevOps Sync Bot"
      git config --global user.email "devops-bot@example.com"

      echo "Adding GitHub remote..."
      git remote add github https://$(github.username):$(github.pat)@github.com/BlackWolves-nl/ProjectReferrerVersioning.git

      echo "Mirroring..."
      git push github --mirror
    displayName: "Mirror to GitHub"
