trigger:
  branches:
    include:
      - "*"   # run on every branch push

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true
    clean: true

  # Download credentials from service connection
  - task: GitHubAuthenticate@0
    inputs:
      authType: 'ServiceConnection'
      serviceConnection: 'GithubMirrorConnection'
    name: githubAuth

  - script: |
      echo "Configuring Git identity..."
      git config --global user.name "Azure DevOps Sync Bot"
      git config --global user.email "devops-bot@example.com"

      echo "Adding GitHub remote from service connection..."
      git remote add github https://$(GITHUB_USER):$(GITHUB_PAT)@github.com/BlackWolves-nl/ProjectReferrerVersioning.git

      echo "Mirroring all branches and tags to GitHub..."
      git push github --mirror
    displayName: "Mirror to GitHub"
